name: flutter_future_progress_dialog
description: Allows to display progress dialog while the Future function is evaluated.
version: 1.3.0
homepage: https://github.com/nerdy-pro/flutter-progress-dialog

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
