name: Publish to pub.dev

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Publish to pub.dev'
        required: true
        default: 'publish'

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  publish:
    name: Publish to pub.dev
    needs: [ test ]
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub_publish # Use this environment for approval
      working-directory: .